// React/src/App.js
import { useEffect, useRef, useState } from 'react';
import './App.css';
function App() {
  const [podsjetnici, setpodsjetnici] = useState([]);
  const podsjetnikText = useRef();
  useEffect(() => {
    const existingpodsjetnici = localStorage.getItem('podsjetnici');
    setpodsjetnici(existingpodsjetnici ? JSON.parse(existingpodsjetnici) : []);
  }, []);
  function addPodsjetnik(event) {
    event.preventDefault();
    const next = [...podsjetnici, podsjetnikText.current.value];
    setpodsjetnici(next);
    localStorage.setItem('podsjetnici', JSON.stringify(next));
  }
  return (
    <div>
      <ul class="podsjetnici">
        {podsjetnici.map(podsjetnik => (<li key={podsjetnik}>{podsjetnik}</li>))}  
      </ul>
      <form class="card" onSubmit={addPodsjetnik}>
        <input type="text" placeholder="Napiši zadatak" ref={podsjetnikText} />
        <input type="submit" value="Dodaj podsjetnik" />
      </form>
    </div>
  );
}
export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {  
  podsjetnici: string[] = [];
  podsjetnikText = '';
  ngOnInit() {
    const existingPodjsetnici = localStorage.getItem('podsjetnici');
    this.podsjetnici = JSON.parse(existingPodjsetnici as string) || [];
  }
  addPodsjetnik() {
    this.podsjetnici.push(this.podsjetnikText);
    localStorage.setItem('podsjetnici', JSON.stringify(this.podsjetnici));
  }
}
<div class="body">
  <ul class="podsjetnici">
    <li *ngFor="let podsjetnik of podsjetnici">{{podsjetnik}}</li>
  </ul>
<form class="card" (ngSubmit)="addPodsjetnik()">
  <input  name="podsjetniktext" [(ngModel)]="podsjetnikText">
  <input type="submit" value="Dodaj podsjetnik">
</form>
</div>
